name: Privado Scan
on: push
    
jobs:
  privado:
    runs-on: ubuntu-latest
    if: github.ref_name == github.event.repository.default_branch
    env:
      PRIVADO_API_TOKEN: ${{ secrets.PRIVADO_API_TOKEN }}
      PRIVADO_API_ID: "06e88742-f97a-428a-97b9-d7c3ca44c273"
      PRIVADO_API_HOST: "https://t.api.code.privado.ai/test"
      PRIVADO_CI_PLATFORM: "GITHUB_ACTIONS"
      PRIVADO_DOCKER_IMAGE: 638117407428.dkr.ecr.ap-south-1.amazonaws.com/scanner-agent:latest-dockerless
      PRIVADO_REPOSITORY_ID: ${{ github.repository_id }}
      PRIVADO_REPOSITORY_NAME: ${{ github.repository }}
      PRIVADO_COMMIT_ID: ${{ github.sha }}
      PRIVADO_BRANCH_NAME: ${{ github.ref_name }}
      PRIVADO_DEFAULT_BRANCH_NAME: ${{ github.event.repository.default_branch }}
      PRIVADO_REPOSITORY_URL: ${{ github.repositoryUrl }}
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: "Login to docker registry"
      run: |
        curl --fail -s -H "Content-Type: application/json" -H "Authorization: Token $PRIVADO_API_TOKEN" -H "idt: $PRIVADO_API_TOKEN" -H "data-url: /ce/integrations/customers/$PRIVADO_API_ID/docker-registry-token" $PRIVADO_API_HOST/ce/integrations/customers/$PRIVADO_API_ID/docker-registry-token?ci=true | docker login --username AWS --password-stdin $PRIVADO_DOCKER_IMAGE
    - name: Run Privado Scanner
      run: |
        env | grep "PRIVADO_" > $GITHUB_WORKSPACE/.privado.env
        env
        docker run -t -v $GITHUB_WORKSPACE:/privado --env-file $GITHUB_WORKSPACE/.privado.env --privileged --pull=always $PRIVADO_DOCKER_IMAGE
